//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ERepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTaskInsertLog
    {
        public int TaskInsertLogID { get; set; }
        public Nullable<int> TotalRowInserted { get; set; }
        public Nullable<int> TotalEmployeeCount { get; set; }
        public string LoadStatus { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> TaskCreatedOn { get; set; }
        public string TaskCreatedBy { get; set; }
    }
}
