//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ERepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReviewComment
    {
        public int CommentID { get; set; }
        public string CommendDescription { get; set; }
        public int ReviewerID { get; set; }
        public int EmployerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string IsDefault { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
