//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ERepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMI
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ResetCode { get; set; }
        public Nullable<int> FailAttempts { get; set; }
        public Nullable<int> IsBlocked { get; set; }
    }
}
