//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ERepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserAccountID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public int EmployerID { get; set; }
        public Nullable<int> WebAppAdminID { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public Nullable<int> AdminUserID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmployerAdmin EmployerAdmin { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
