//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2ERepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAppOwner
    {
        public int AppOwnerAdminId { get; set; }
        public string BusinessName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string zip { get; set; }
        public string BusinessPhoneNumber { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string PrimaryEmail { get; set; }
        public string BusinessEmail1 { get; set; }
        public string BusinessEmail2 { get; set; }
        public string Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public int RoleID { get; set; }
        public int EmployerID { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual E2E_UserRole E2E_UserRole { get; set; }
    }
}
